# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20160623_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='type',
            field=models.IntegerField(choices=[(0, 'setting'), (1, 'file')], default=0, verbose_name='Type'),
        ),
    ]
