# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='devel',
            field=models.CharField(blank=True, default=None, max_length=60, verbose_name='Development Tree'),
        ),
    ]
