# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20160625_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='devel',
            field=models.CharField(blank=True, max_length=60, verbose_name='Development Tree'),
        ),
    ]
