# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patch', '0001_initial'),
        ('repository', '0002_auto_20160625_1051'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTaskQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('filename', models.CharField(blank=True, max_length=256, verbose_name='File Name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.RepositoryTag', verbose_name='Repository Tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.PatchType', verbose_name='Patch Type')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTaskQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patch.Patch', verbose_name='Patch')),
            ],
        ),
    ]
