# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantaskqueue',
            name='flags',
            field=models.IntegerField(default=0, verbose_name='Flags'),
        ),
    ]
